### ISSUE TITLE
Auditing of changes in database

### ISSUE THREAD

**Issue by davidekh** [lbenda/DBApp#31]
Čau,
Vidím, že už na tom sice moc neděláš. Ale když by jsi náhodou našel čas a myslíš, že to dává smysl, uvítal bych možnost ukládat změny do logu (stačí předchozí hodnota nebo smazaný záznam). 

Historizovat celou databázi není úplně praktické.

Díky,
David

**Comment by lbenda** [comment]
Jo určitě dává smysl vytvořit logovací tabulky se všemi změnami. Asi formou nějakých XML záznamů, kde bude popis toho co se stalo. Jako spuštění SQL, nebo přidání hodnoty z aplikace.
